# Site settings
title: Programmable Production
description: >
    For developer who want to learn devops
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://blog.programmableproduction.com" # the base hostname & protocol for your site

#Author Settings
author: Programmable Production
author-img: david-zucker.jpg
author-about: For developer who like to learn about devops  

social-github:  davzucky
social-email: david@programmableproduction.com
social-linkedin: david-zucker-5909a01

permalink: /:year/:month/:day/:title/

#Disqus
disqus-identifier: programmableproduction

#google analytic
google-analytics: UA-73704356-1
google-site-verification: 1HoCUONq0k9sykDYxzVYL3pbrm1hiEraInE8GN_BaRA

#Move the sass folder under assets
sass:
     sass_dir: assets/css
